### PR TITLE
basic automatic id column implementation

### PR DESCRIPTION
**Pull request by KCErb**
Howdy!

Finally got to pushing this up. This is just my first commit. I got side tracked for a bit and almost included a feature implementing delete so that I could test `AUTOINCREMENT` here but I figured I'll leave that off and start with something basic here.

Some thoughts about stuff to add to this commit
- Right now I put in a very weak guard that doesn't allow 'id' to be the `column_name` for a few types. Sorta random just a quick patch. It definitely needs to be replaced. I'm tempted to go a little more heavy handed like throwing an error and quitting: "hey you can't use `id` as a column name unless you pass `id: false` into entity"!

which brings me to the next idea
- How about adding an `opts` hash to `entity` so that we can determine whether or not to add an `id` based on user's preference.

Next time slot (tomorrow morning) I'll start implementing that unless I hear nay from you @jsilverMDX.

### CODE REVIEW

**Comment by mixflame** [comment]
Hey KC.

No objections here. I think declaring it (the primary key) on the columns in the schema is a good idea. I think if the options aren't passed to the column, we should assume :id is false for that column. If no id is set for the whole entity, we'll use "id". If an improper id is set, like a boolean or a string, we'll throw an error and exit. We should also throw an error and exit if there are two id columns declared. If an integer column is used, we should AUTOINCREMENT and use that as PRIMARY KEY. 

Thank you for your awesome work! :D :us:

**Comment by KCErb** [comment]
OK cool. I just started working on this and I noticed something worth discussing.

In the docs we get this:

`The PRIMARY KEY is optional for ordinary tables but is required for WITHOUT ROWID tables.`

I'm not interested in supporting WITHOUT ROWID tables at the moment, but I like the idea of specifying that when you kill our automatic `id` by passing `id: false` then you must specify its successor.

Agreed?

So I think we need something like this. In other words, if you are intending to use something other than the auto-generated id then you need to pass `id: false` (so that we don't generate one) into `entity`  and then in one of the rows of your schema you need to specify a primary key. 

``` ruby
entity "Car", id: false do
  boolean :is_red
  integer :mileage, primary_key: true
end
```

With that done I'm not sure yet if they would need to set the primary key from the class. We can probably retrieve it but I'll see about that soon.

Thoughts?

**Comment by mixflame** [comment]
Looks good to me.

You're correct it might be possible to infer primary id from the schema declaration. We want to infer as much of that as possible (the class name and the primary key.) If we can get it fully automatic we'll look as magic as AR.

:D :+1:

**Comment by mixflame** [comment]
Since the overall idea of this pull request (force them to have id column by default, don't allow creation of id column) makes sense. I'm going to merge it. We can build on it more as discussed above but the general idea here is correct. Merging.

**Comment by mixflame** [comment]
I agree with your methodology. I don't think we need to support WITHOUT
ROWID until it definitely comes up with a use case. I don't believe the
docs that it's sometimes useful. It just seems like the SQLite way of
forcing a row id. I think we can do better at a higher level of ruby with
the exact syntax you suggested. Totally agreed.

**Comment by mixflame** [comment]
And by I don't believe them, I mean without a sample and test result data.

**Pull request merged**
